doctrine:
    orm:
        entity_managers:
            default:
                auto_mapping: true
                dql:
                    datetime_functions:
                        date: Baetmaen\DqlBundle\Dql\Date
                        day: Baetmaen\DqlBundle\Dql\Day
                        month: Baetmaen\DqlBundle\Dql\Month
                        year: Baetmaen\DqlBundle\Dql\Year
                        hour: Baetmaen\DqlBundle\Dql\Hour
                        week: Baetmaen\DqlBundle\Dql\Week