parameters:
#    baetmaen_dql.example.class: Baetmaen\DqlBundle\Example

services:
#    baetmaen_dql.example:
#        class: %baetmaen_dql.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
